#requires -version 5.1
[CmdletBinding()]
param([string]$InstallPath="",[switch]$Rollback,[switch]$Force)
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Windows.Forms
[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12

$Target='qwen3vl_32b_h3_ultra_heretic_int8_convrot.safetensors'
$Official='qwen3vl_32b_minimax_h3_(bf16|int8_convrot|nvfp4_awq)\.safetensors'
$T2V='MiniMax_H3_Heretic_T2V.json'
$I2V='MiniMax_H3_Heretic_I2V.json'
$State='h3-heretic-isolated-state.json'
$Repos=@('ethanfel/Qwen3-VL-32B-Ultra-Heretic-H3-ComfyUI-INT8-ConvRot','ethanfel/Qwen3-VL-32B-Ultra-Heretic-MiniMax-H3-ComfyUI-INT8-ConvRot')
$script:Root=$null
function Log([string]$m,[string]$l='INFO'){$s='[{0}] [{1}] {2}'-f(Get-Date -Format 'yyyy-MM-dd HH:mm:ss'),$l,$m;Write-Host $s;if($script:Root){try{Add-Content (Join-Path $script:Root 'h3-heretic-isolated.log') $s -Encoding UTF8}catch{}}}
function Prop($o,[string]$n){if($null-eq$o){return $null};$p=$o.PSObject.Properties[$n];if($p){return $p.Value};return $null}
function Valid([string]$p){return $p-and(Test-Path(Join-Path $p 'ComfyUI\models\text_encoders'))}
function Root([string]$p){foreach($x in @($p,$env:MINIMAX_H3_HOME,'D:\MiniMaxH3','C:\MiniMaxH3','E:\MiniMaxH3','F:\MiniMaxH3')){if(Valid $x){return[IO.Path]::GetFullPath($x)}};$d=New-Object Windows.Forms.FolderBrowserDialog;$d.Description='请选择 MiniMax H3 安装根目录';if($d.ShowDialog()-eq'OK'-and(Valid $d.SelectedPath)){return[IO.Path]::GetFullPath($d.SelectedPath)};throw'未找到有效 MiniMax H3 安装目录。'}
function Ram(){try{return[math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory/1GB,1)}catch{return 0}}
function Free([string]$p){$r=[IO.Path]::GetPathRoot([IO.Path]::GetFullPath($p));return[math]::Round((New-Object IO.DriveInfo($r)).AvailableFreeSpace/1GB,1)}
function OfficialWorkflow(){foreach($p in @((Join-Path $script:Root 'ComfyUI\user\default\workflows\MiniMax_H3_8GB.json'),(Join-Path $script:Root 'workflows\MiniMax_H3_8GB.json'))){if(Test-Path $p){return$p}};foreach($d in @((Join-Path $script:Root 'ComfyUI\user'),(Join-Path $script:Root 'workflows'))){if(Test-Path $d){foreach($f in Get-ChildItem $d -Filter *.json -File -Recurse -ErrorAction SilentlyContinue){if($f.Name-in@($T2V,$I2V)){continue};try{$r=[IO.File]::ReadAllText($f.FullName);if($r-match$Official-and$r-match'MiniMax'){return$f.FullName}}catch{}}}};throw'没有找到官方 MiniMax H3 工作流。'}
function Remote(){foreach($repo in $Repos){foreach($base in @('https://hf-mirror.com','https://huggingface.co')){try{Log "读取模型清单：$base";$i=Invoke-RestMethod "${base}/api/models/${repo}?blobs=true" -TimeoutSec 45 -Headers @{'User-Agent'='H3-Heretic-Isolated/2.0'};$fs=@((Prop $i 'siblings')|?{$n=([string](Prop $_ 'rfilename')).ToLower();$n.EndsWith('.safetensors')});$c=@($fs|?{$n=([string](Prop $_ 'rfilename')).ToLower();$n-match'int8'-and$n-match'convrot'-and$n-notmatch'int4|nvfp4|fp8|bf16|fp16'});if($c.Count-eq0){$c=@($fs|?{$n=([string](Prop $_ 'rfilename')).ToLower();$n-match'int8'-and$n-notmatch'int4|nvfp4|fp8|bf16|fp16'})};if($c.Count-eq0-and$fs.Count-eq1){$c=$fs};if($c.Count){$f=$c|Select-Object -First 1;$l=Prop $f 'lfs';$z=Prop $f 'size';if((-not$z)-and$l){$z=Prop $l 'size'};if(-not$z){$z=0};$h=$null;if($l){$h=Prop $l 'sha256';if(-not$h){$o=[string](Prop $l 'oid');if($o-match'^sha256:([0-9a-fA-F]{64})$'){$h=$Matches[1]}elseif($o-match'^[0-9a-fA-F]{64}$'){$h=$o}}};return[pscustomobject]@{Repo=$repo;Name=[string](Prop $f 'rfilename');Size=[int64]$z;Sha=[string]$h}}}catch{Log $_.Exception.Message 'WARN'}}};throw'无法确定 Heretic INT8 ConvRot 模型文件。'}
function Download($m,[string]$dst){$curl=Get-Command curl.exe -ErrorAction SilentlyContinue;if(-not$curl){throw'未找到 Windows 自带 curl.exe。'};$part="$dst.part";$name=[Uri]::EscapeDataString($m.Name).Replace('%2F','/');foreach($base in @('https://hf-mirror.com','https://huggingface.co')){$url="${base}/$($m.Repo)/resolve/main/${name}?download=true";Log "下载：$url";$args=@('-L','--fail','--connect-timeout','20','--retry','2','-C','-','-o',$part,$url);&$curl.Source @args;if($LASTEXITCODE-eq0){if($m.Size-gt0-and(Get-Item $part).Length-ne$m.Size){Log '下载大小不匹配，尝试下一源' 'WARN';continue};Move-Item $part $dst -Force;return};Log "下载源失败，代码 $LASTEXITCODE" 'WARN'};throw'镜像与官方源均下载失败。'}
function SafeTensor([string]$p){$f=[IO.File]::OpenRead($p);try{$b=New-Object byte[] 8;if($f.Read($b,0,8)-ne8){return$false};$h=[BitConverter]::ToUInt64($b,0);return$h-gt2-and$h-lt268435456-and($h+8)-lt[uint64]$f.Length}finally{$f.Dispose()}}
function MakeT2V([string]$src,[string]$dst){$r=[IO.File]::ReadAllText($src);[void]($r|ConvertFrom-Json);$r=[regex]::Replace($r,$Official,$Target);[void]($r|ConvertFrom-Json);[IO.File]::WriteAllText($dst,$r,(New-Object Text.UTF8Encoding($false)))}
function MakeI2V([string]$src,[string]$dst){$r=[regex]::Replace([IO.File]::ReadAllText($src),$Official,$Target);$w=$r|ConvertFrom-Json;$t=$null;foreach($n in @($w.nodes)){$ff=$false;foreach($i in @($n.inputs)){if([string](Prop $i 'name')-eq'first_frame'){$ff=$true;break}};if($ff-and((Prop $n 'widgets_values')|ConvertTo-Json -Compress)-match'minimax_h3'){$t=$n;break}};if(-not$t){throw'无法定位 H3 first_frame 输入，拒绝生成图生视频工作流。'};$ix=-1;for($i=0;$i-lt@($t.inputs).Count;$i++){if([string](Prop $t.inputs[$i] 'name')-eq'first_frame'){$ix=$i;break}};if($ix-lt0){throw'找不到 first_frame 输入索引。'};if($null-eq(Prop $t.inputs[$ix] 'link')){$mn=0;foreach($n in @($w.nodes)){$id=Prop $n 'id';if(($id-is[int]-or$id-is[long])-and[int64]$id-gt$mn){$mn=[int64]$id}};$ml=0;foreach($l in @($w.links)){if($l-and@($l).Count){$id=[int64]$l[0];if($id-gt$ml){$ml=$id}}};$nid=[int]($mn+1);$lid=[int]($ml+1);$tid=[int](Prop $t 'id');$load=[pscustomobject]@{id=$nid;type='LoadImage';pos=@(-2050,5530);size=@(360,360);flags=[pscustomobject]@{};order=0;mode=0;inputs=@();outputs=@([pscustomobject]@{name='IMAGE';type='IMAGE';links=@($lid)},[pscustomobject]@{name='MASK';type='MASK';links=$null});title='载入首帧（Heretic 图生视频）';properties=[pscustomobject]@{'Node name for S&R'='LoadImage'};widgets_values=@('example.png','image')};$t.inputs[$ix].link=$lid;$w.nodes=@($w.nodes)+@($load);$w.links=@($w.links)+@(,@($lid,$nid,0,$tid,$ix,'IMAGE'));if($w.PSObject.Properties['last_node_id']){$w.last_node_id=$nid};if($w.PSObject.Properties['last_link_id']){$w.last_link_id=$lid}};$j=$w|ConvertTo-Json -Depth 100;[IO.File]::WriteAllText($dst,$j,(New-Object Text.UTF8Encoding($false)));[void]([IO.File]::ReadAllText($dst)|ConvertFrom-Json)}
function RemoveCustom(){foreach($p in @((Join-Path $script:Root "ComfyUI\user\default\workflows\$T2V"),(Join-Path $script:Root "ComfyUI\user\default\workflows\$I2V"))){if(Test-Path $p){Remove-Item $p -Force;Log "移除 $p"}};$s=Join-Path $script:Root $State;if(Test-Path $s){Remove-Item $s -Force}}
try{$script:Root=Root $InstallPath;Log "H3 根目录：$script:Root";if($Rollback){RemoveCustom;[Windows.Forms.MessageBox]::Show('已移除 Heretic 专用工作流。官方工作流从未修改。','H3 Heretic','OK','Information')|Out-Null;exit0};$enc=Join-Path $script:Root 'ComfyUI\models\text_encoders';$off=@(Get-ChildItem $enc -File|?{$_.Name-match('^'+$Official+'$')});if(-not$off.Count){throw'未检测到官方 H3 encoder，拒绝操作。'};$src=OfficialWorkflow;Log "官方工作流保持原样：$src";$ram=Ram;if(-not$Force-and$ram-gt0-and$ram-lt48){throw"INT8 Heretic 建议至少 48GB 内存；当前 $ram GB。未修改任何文件。"};$m=Remote;$need=if($m.Size-gt0){[math]::Ceiling($m.Size/1GB)+5}else{35};if((Free $script:Root)-lt$need){throw"磁盘空间不足，至少需要约 $need GB。"};$dst=Join-Path $enc $Target;if(-not(Test-Path $dst)){Download $m $dst};if($m.Size-gt0-and(Get-Item $dst).Length-ne$m.Size){throw'模型大小校验失败。'};if($m.Sha){Log '校验 SHA-256';$h=(Get-FileHash $dst -Algorithm SHA256).Hash;if($h.ToLower()-ne$m.Sha.ToLower()){throw'SHA-256 校验失败。'}};if(-not(SafeTensor $dst)){throw'safetensors 结构校验失败。'};$wd=Join-Path $script:Root 'ComfyUI\user\default\workflows';New-Item -ItemType Directory -Force $wd|Out-Null;$tp=Join-Path $wd $T2V;$ip=Join-Path $wd $I2V;MakeT2V $src $tp;MakeI2V $src $ip;$s=[pscustomobject]@{SourceOfficialWorkflow=$src;T2VWorkflow=$tp;I2VWorkflow=$ip;TargetEncoder=$Target;Timestamp=(Get-Date).ToString('o')};[IO.File]::WriteAllText((Join-Path $script:Root $State),($s|ConvertTo-Json -Depth 5),(New-Object Text.UTF8Encoding($false)));Log '完成：官方工作流 0 修改；新增 Heretic T2V + I2V。';[Windows.Forms.MessageBox]::Show("已新增：`r`n$T2V`r`n$I2V`r`n`r`n官方 MiniMax_H3_8GB.json 完全未修改。",'H3 Heretic','OK','Information')|Out-Null}catch{Log $_.Exception.Message 'ERROR';[Windows.Forms.MessageBox]::Show($_.Exception.Message,'H3 Heretic','OK','Error')|Out-Null;exit1}
